using FBEVJKGADQD.Protocol;

namespace FBEVJKGADQD.Gameserver.CWREKSPCAGC.KRACKSBFMLI.CJFUHOXIYCR;
internal interface ZKTZSOLHWMF
{
    ValueTask UEAOFOPRVGJ(STEHGLSHISK NXUAOYXTYSI, VisionType IFYZWPCNRTU);
}
