using FBEVJKGADQD.Gameserver.CWREKSPCAGC.MAFLNNQAYHC;

namespace FBEVJKGADQD.Gameserver.CWREKSPCAGC.KRACKSBFMLI.XSUUHMCVMKJ;
internal class NJKLKSSIKNA
{
    private uint XLLSPZAMTJQ;

    public NXIDDMLGEYM OGYPYOJHSJZ(NXBLJJGQFZU MLWDJIMREEA, uint TKXWQFGUKZD)
    {
        return new(MLWDJIMREEA, TKXWQFGUKZD, ++XLLSPZAMTJQ);
    }
}
